[package]
name = "example-server"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
neva = { path = "../../neva" }
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.1", features = ["full"] }
