[package]
name = "server"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
publish = false

[dependencies]
neva = { path = "../../../neva", features = ["server-full"] }
tokio = { version = "1.44.1", features = ["full"] }