[package]
name = "server"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
neva = { path = "../../../neva", features = ["macros"] }
tokio = { version = "1.44.1", features = ["full"] }