name: Release

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    environment: CICD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        
      - name: Publish neva_macros
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --manifest-path neva_macros/Cargo.toml
        
      - name: Wait for index update
        run: sleep 30
        
      - name: Publish neva
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --manifest-path neva/Cargo.toml