name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run all features
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run slim server
        run: cargo clippy --all-targets --features server -- -D warnings
      - name: Run server with macros
        run: cargo clippy --all-targets --features server-macros -- -D warnings
      - name: Run http server
        run: cargo clippy --all-targets --features http-server -- -D warnings
      - name: Run all features server
        run: cargo clippy --all-targets --features server-full -- -D warnings
      - name: Run slim client
        run: cargo clippy --all-targets --features client -- -D warnings
      - name: Run client with macros
        run: cargo clippy --all-targets --features client-macros -- -D warnings
      - name: Run http client
        run: cargo clippy --all-targets --features http-client -- -D warnings
      - name: Run all features client
        run: cargo clippy --all-targets --features client-full -- -D warnings
  
  build:
    environment: CICD
    runs-on: ubuntu-latest
    needs: clippy_check

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run all features tests
        run: cargo test --all-features --verbose
      - name: Run server tests
        run: cargo test --features server-full --verbose
      - name: Run client tests
        run: cargo test --features client-full --verbose